name: Blog CI/CD # 脚本 workflow 名称

on:
  push:
    branches: [main, master] # 当监测 main,master 的 push
    paths: # 监测的路径。
      - '*.json'
      - '**.yml'
      - '**/source/**'
      - '**/scaffolds/**'
      - '**/themes/**'

jobs:
  deploy: # 任务名称
    runs-on: ubuntu-latest # 指定最新 ubuntu 系统
    steps:
      - uses: actions/checkout@v4 # 拉取仓库代码
      - name: Use Node.js 18
        uses: actions/setup-node@v4 # 设置 node.js 环境
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: "18"
      - name: Cache node_modules # 缓存 node_modules，提高编译速度，毕竟每月只有 2000 分钟。
        uses: actions/cache@v4 # 亲测 Github 服务器编译速度比我自己电脑都快，如果每次构建按5分钟计算，我们每个月可以免费部署 400 次，Github yyds！！！
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies # 安装源代码所需插件
        run: npm install
      - name: Install Hexo-cli # 安装 Hexo
        run: npm install -g hexo-cli --save
      - name: Build Blog # 编译创建静态博客文件
        run: |
          hexo clean
          hexo g
      - name: Deploy Blog # 设置 git 信息并推送静态博客文件
        run: |
          git config --global user.name "sonjayce"
          git config --global user.email "3489073251@qq.com"
          hexo deploy

      - run: echo "Deploy Finished!"
